Repository FromDoppler/doppler-beplic, pull requests merged in 2023-11, with the labels that each got.

#48 chore: update fromdoppler.yml
  .github/workflows/fromdoppler.yml
Labels: size/XS

#56 [No-ticket] Change Beplic API base url
  doppler-beplic/appsettings.Development.json
  doppler-beplic/appsettings.int.json
  doppler-beplic/appsettings.qa.json
  global.json
Labels: size/S

#53 [DOI-1067] New endpoint to get plan balance
  doppler-beplic/Models/Responses/PlanBalanceResponse.cs
  doppler-beplic/Program.cs
  doppler-beplic/Services/Classes/BeplicSdk.cs
  doppler-beplic/Services/Classes/BeplicService.cs
  doppler-beplic/Services/Interfaces/IBeplicService.cs
Labels: size/L
