Repository FromDoppler/doppler-beplic, pull requests merged in 2024-08, with the labels that each got.

#85 Get whatsapp rooms
  DopplerBeplic.Tests/GetRoomsTests.cs
  doppler-beplic/Models/Responses/BeplicResponses/BeplicRoomResponse.cs
  doppler-beplic/Models/Responses/RoomResponse.cs
  doppler-beplic/Program.cs
  doppler-beplic/Services/Classes/BeplicSdk.cs
  doppler-beplic/Services/Classes/BeplicService.cs
  doppler-beplic/Services/Interfaces/IBeplicService.cs
Labels: size/L

#86 Get whatsapp templates
  DopplerBeplic.Tests/GetTemplatesTests.cs
  doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateResponse.cs
  doppler-beplic/Models/Responses/TemplateResponse.cs
  doppler-beplic/Program.cs
  doppler-beplic/Services/Classes/BeplicService.cs
  doppler-beplic/Services/Interfaces/IBeplicService.cs
Labels: size/L

#87 fix error messages
  doppler-beplic/Services/Classes/BeplicService.cs
Labels: size/S

#88 Send template message
  DopplerBeplic.Tests/SendTemplateMessageTests.cs
  doppler-beplic/Models/DTO/TemplateMessageDTO.cs
  doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateMessageResponse.cs
  doppler-beplic/Models/Responses/TemplateMessageResponse.cs
  doppler-beplic/Program.cs
  doppler-beplic/Services/Classes/BeplicService.cs
  doppler-beplic/Services/Interfaces/IBeplicService.cs
Labels: size/L

#89 [DAT-2122] Update url for production
  doppler-beplic/appsettings.json
Labels: size/XS

#92 Add logs for errors
  doppler-beplic/Services/Classes/BeplicService.cs
Labels: size/XS

#95 Add RestClientExtensions
  doppler-beplic/Services/Classes/BeplicSdk.cs
  doppler-beplic/Services/Classes/RestClientExtensions.cs
Labels: size/M

#97 Add template preview
  doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateResponse.cs
  doppler-beplic/Models/Responses/TemplateResponse.cs
  doppler-beplic/Services/Classes/BeplicSdk.cs
  doppler-beplic/Services/Classes/BeplicService.cs
Labels: size/M

#98 Add template filter
  doppler-beplic/Services/Classes/BeplicService.cs
Labels: size/XS

#101 Add IsFree property
  doppler-beplic/Models/Responses/PlanResponse.cs
Labels: size/XS

#102 Get user plan
  doppler-beplic/Models/Responses/BeplicResponses/BeplicUserPlanResponse.cs
  doppler-beplic/Models/Responses/UserPlanResponse.cs
  doppler-beplic/Program.cs
  doppler-beplic/Services/Classes/BeplicService.cs
  doppler-beplic/Services/Interfaces/IBeplicService.cs
Labels: size/M

#105 Dat 2160
  doppler-beplic/Models/DTO/PlanCreationDTO.cs
  doppler-beplic/doppler-beplic.csproj
Labels: size/XS
